### ISSUE TITLE
Facing issue in Configuring the Datadog Add for Splunk.

### ISSUE THREAD

**Issue by bhagadkarakash** [splunk/ta-splunk-add-on-for-datadog-api#3]
HI Team,

we have tried to configue the datadog addon with splunk with APP and APi Key but we are not able to fetch logs in splunk.
We have tested with Rest APi to get the detail from Datadog and its working fine with same APP and API key.
we are getting below error in app logs.

2021-04-07 06:07:25,412 INFO pid=11648 tid=MainThread file=setup_util.py:log_info:117 | Log level is not set, use default INFO
2021-04-07 06:07:25,413 INFO pid=11648 tid=MainThread file=splunk_rest_client.py:_request_handler:105 | Use HTTP connection pooling
2021-04-07 06:07:25,464 INFO pid=11648 tid=MainThread file=setup_util.py:log_info:117 | Proxy is not enabled!
2021-04-07 06:07:25,476 WARNING pid=11648 tid=MainThread file=connectionpool.py:urlopen:745 | Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000B6FC0DC708>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': //app.datadoghq.com/api/v1/query?&from=1617753600&to=1617790045&query=system.core.system%7B*%7Dby%7Bhost%7D
2021-04-07 06:07:25,476 WARNING pid=11648 tid=MainThread file=connectionpool.py:urlopen:745 | Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000B6FC0D9688>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': //app.datadoghq.com/api/v1/query?&from=1617753600&to=1617790045&query=system.core.system%7B*%7Dby%7Bhost%7D
2021-04-07 06:07:25,477 WARNING pid=11648 tid=MainThread file=connectionpool.py:urlopen:745 | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000B6FC0D9B88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': //app.datadoghq.com/api/v1/query?&from=1617753600&to=1617790045&query=system.core.system%7B*%7Dby%7Bhost%7D
2021-04-07 06:07:25,485 ERROR pid=11648 tid=MainThread file=base_modinput.py:log_error:309 | Get error when collecting events.
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\urllib3\connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Program Files\Splunk\Python-3.7\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\urllib3\connection.py", line 334, in connect
    conn = self._new_conn()
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000000B6FC0D9188>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='app.datadoghq.https', port=443): Max retries exceeded with url: //app.datadoghq.com/api/v1/query?&from=1617753600&to=1617790045&query=system.core.system%7B*%7Dby%7Bhost%7D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000B6FC0D9188>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\modinput_wrapper\base_modinput.py", line 128, in stream_events
    self.collect_events(ew)
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\datadog_metric_inventory.py", line 84, in collect_events
    input_module.collect_events(self, ew)
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\input_module_datadog_metric_inventory.py", line 176, in collect_events
    headers=headers, cookies=None, verify=True, cert=None, timeout=None, use_proxy=True)
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\modinput_wrapper\base_modinput.py", line 478, in send_http_request
    proxy_uri=self._get_proxy_uri() if use_proxy else None)
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\splunk_aoblib\rest_helper.py", line 43, in send_http_request
    return self.http_session.request(method, url, **requests_args)
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Splunk\etc\apps\TA-splunk-add-on-for-datadog-api\bin\ta_splunk_add_on_for_datadog_api\aob_py3\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='app.datadoghq.https', port=443): Max retries exceeded with url: //app.datadoghq.com/api/v1/query?&from=1617753600&to=1617790045&query=system.core.system%7B*%7Dby%7Bhost%7D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000B6FC0D9188>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by dfederschmidt** [comment]
Hi @bhagadkarakash,

Please ensure that the **Datadog Site** in the Account configuration contains either  `com` if you're connecting to the US site or `eu` in case of europe. Please do not enter the full datadog API endpoint URL here! 
The README outlines this as well under [step 3](https://github.com/splunk/ta-splunk-add-on-for-datadog-api).
 
Hope this will resolve the issue you're facing!
